#!/usr/bin/env node
// Installs the hook (PreToolUse.cjs + generated jev-hook-lib.js) into the Cline
// hooks directory so that EVERY ask_question / ask_followup_question is scored
// with Jev before it runs. Also regenerates hooks/jev-hook-lib.js in the repo.
//
// HOW CLINE DISCOVERS HOOK FILES (from @cline/core):
//   1. it scans each existing hooks search path - non-recursively - and picks
//      files whose extension is one of "", .sh, .bash, .zsh, .js, .mjs, .cjs,
//      .ts, .mts, .cts, .py, .ps1;
//   2. the basename (lowercased, extension stripped) must be a hook event name,
//      e.g. `PreToolUse.cjs` -> "pretooluse" -> PreToolUse -> tool_call;
//   3. EVERY matching file runs (results applied in path order), so a stray
//      `pretooluse.sh` next to this one would also run. We warn about that.
//
// Usage:
//   npm run install:hook                     # -> ~/.cline/hooks/PreToolUse.cjs
//   node scripts/install-hook.mjs --dir <d>  # custom hooks dir
import { chmodSync, existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const REPO = join(here, "..");
const HOOK_ENTRY = join(REPO, "hooks", "PreToolUse.cjs");
const POST_ENTRY = join(REPO, "hooks", "PostToolUse.cjs");
// .cjs on purpose: inside a "type": "module" repo a .js lib would be loaded as
// ESM and its require() header would throw. .cjs is CommonJS everywhere.
const HOOK_LIB = join(REPO, "hooks", "jev-hook-lib.cjs");
const CONFIG_SOURCE = join(REPO, "src", "jev-config.js");
const CORE_SOURCE = join(REPO, "src", "jev-hook-core.js");

// The installed hook runs standalone (no node_modules beside it), so the lib
// is GENERATED from the src/ files: config + core concatenated, `export`
// stripped for CommonJS. Fail closed on any missing piece so a half-built lib
// can never be installed.
function buildLibSource() {
  const config = readFileSync(CONFIG_SOURCE, "utf8");
  const core = readFileSync(CORE_SOURCE, "utf8");
  const strip = (src) =>
    src
      .split("\n")
      .filter((l) => !/^import\s+[{\w][^;]*from\s+["'](?:node:|\.\/jev-config\.js)/.test(l))
      // The ESM createRequire/__req bootstrap is replaced by the generated
      // header below — drop the source lines so nothing is declared twice.
      .filter((l) => !/^\s*const __req\s*=/.test(l))
      .join("\n")
      .replace(/^export\s+/gm, "")
      // import.meta has no meaning in CJS: the generated lib runs beside the
      // installed hook, so __filename-equivalent resolution uses module paths.
      .replace(/__createRequire\(import\.meta\.url\)/g, "__createRequire(__filename)");
  const configBody = strip(config);
  const coreBody = strip(core);
  for (const [name, body] of [
    ["resolveConfig", configBody],
    ["configPaths", configBody],
    ["main", coreBody],
    ["postMain", coreBody],
  ]) {
    if (!body.includes(`function ${name}`)) {
      console.error(`[install-hook] ${name}() missing from built lib - refusing to install`);
      process.exit(1);
    }
  }
  return (
    `// jev-hook-lib.js — GENERATED by scripts/install-hook.mjs. DO NOT EDIT.\n` +
    `// Built from: src/jev-config.js (config) + src/jev-hook-core.js (hook logic).\n` +
    `// Regenerate: \`npm run install:hook\` (also refreshes the installed copy).\n` +
    `"use strict";\n` +
    `const { createRequire: __createRequire } = require("node:module");\n` +
    `const __req = typeof require === "function" ? require : __createRequire(__filename);\n` +
    configBody +
    `\n` +
    coreBody +
    `\nmodule.exports = { main, postMain, log, resolveConfig, configPaths };\n`
  );
}

// Target dir comes from --dir only — no CLINE_HOOKS_DIR env lookup.
const argv = process.argv.slice(2);
const dirFlag = argv.indexOf("--dir");
const targetDir = resolve(
  dirFlag >= 0 && argv[dirFlag + 1] ? argv[dirFlag + 1] : join(homedir(), ".cline", "hooks")
);

for (const [label, p] of [
  ["hook entry", HOOK_ENTRY],
  ["post-hook entry", POST_ENTRY],
  ["config source", CONFIG_SOURCE],
  ["core source", CORE_SOURCE],
]) {
  if (!existsSync(p)) {
    console.error(`[install-hook] ${label} not found: ${p}`);
    process.exit(1);
  }
}
mkdirSync(targetDir, { recursive: true });

// The repo copy of the lib is itself generated — rebuild it first so tests
// exercise exactly what gets installed.
const libSource = buildLibSource();
writeFileSync(HOOK_LIB, libSource);

function installOne(name, content) {
  const target = join(targetDir, name);
  if (existsSync(target)) {
    const current = readFileSync(target, "utf8");
    if (current === content) {
      chmodSync(target, 0o755);
      console.log(`[install-hook] already up to date: ${target}`);
      return;
    }
    const backup = `${target}.bak`;
    writeFileSync(backup, current);
    console.log(`[install-hook] backed up previous hook -> ${backup}`);
  }
  writeFileSync(target, content);
  chmodSync(target, 0o755);
  // Fail loudly if the copy is not byte-identical.
  if (readFileSync(target, "utf8") !== content) {
    console.error(`[install-hook] copy verification FAILED for ${target}`);
    process.exit(1);
  }
  console.log(`[install-hook] installed + verified: ${target} (mode 755)`);
}

installOne("PreToolUse.cjs", readFileSync(HOOK_ENTRY, "utf8"));
installOne("PostToolUse.cjs", readFileSync(POST_ENTRY, "utf8"));
// Clean up previously installed .js artifacts so Cline doesn't run both and the
// stale (ESM-fragile) lib isn't left behind.
const oldJs = join(targetDir, "PreToolUse.js");
if (existsSync(oldJs)) {
  unlinkSync(oldJs);
  console.log(`[install-hook] removed stale PreToolUse.js (replaced by PreToolUse.cjs)`);
}
const oldLib = join(targetDir, "jev-hook-lib.js");
if (existsSync(oldLib)) {
  unlinkSync(oldLib);
  console.log(`[install-hook] removed stale jev-hook-lib.js (replaced by jev-hook-lib.cjs)`);
}
installOne("jev-hook-lib.cjs", libSource);

// Prompt steering: the skill + rules tell the model to ask with 2-5 options.
// They are the weakest layer, but without files in ~/.cline no session ever sees
// them. Installed only for the real (~/.cline) target — --dir is a test/dev
// override and must not write into the repo.
if (dirFlag < 0) {
  const clineDir = dirname(targetDir); // <home>/.cline
  const steering = [
    [join(REPO, "skills", "jev-percentages", "SKILL.md"), join(clineDir, "skills", "jev-percentages", "SKILL.md")],
    [join(REPO, ".clinerules"), join(clineDir, "rules", "cline-option-scorer.md")],
  ];
  for (const [src, dst] of steering) {
    if (!existsSync(src)) continue;
    mkdirSync(dirname(dst), { recursive: true });
    const content = readFileSync(src, "utf8");
    if (existsSync(dst) && readFileSync(dst, "utf8") === content) {
      console.log(`[install-hook] already up to date: ${dst}`);
      continue;
    }
    writeFileSync(dst, content);
    console.log(`[install-hook] installed prompt steering: ${dst}`);
  }
}

const EXTENSIONS = new Set(["", ".sh", ".bash", ".zsh", ".js", ".mjs", ".cjs", ".ts", ".mts", ".cts", ".py", ".ps1"]);
const EVENT_NAMES = new Map([
  ["taskstart", "TaskStart"],
  ["taskresume", "TaskResume"],
  ["taskcancel", "TaskCancel"],
  ["taskcomplete", "TaskComplete"],
  ["taskerror", "TaskError"],
  ["pretooluse", "PreToolUse"],
  ["posttooluse", "PostToolUse"],
  ["userpromptsubmit", "UserPromptSubmit"],
  ["precompact", "PreCompact"],
  ["sessionshutdown", "SessionShutdown"],
]);
const hookEventName = (file) => {
  const ext = extname(file).toLowerCase();
  return EXTENSIONS.has(ext) ? EVENT_NAMES.get(basename(file, ext).trim().toLowerCase()) : undefined;
};

const rivals = readdirSync(targetDir).filter((f) => f !== "PreToolUse.cjs" && hookEventName(f) === "PreToolUse");
if (rivals.length) {
  console.warn(
    `[install-hook] warning: ${rivals.join(", ")} also maps to PreToolUse in ${targetDir}; ` +
      `Cline runs every match, so remove it if the question gets scored twice.`
  );
}
console.log("[install-hook] open a NEW Cline session so the hook is picked up;");
console.log("[install-hook] verify with: tail -n 5 ~/.cline/data/logs/jev-hook.jsonl");
